version: '3'

services:

  #finance microservice start
  finance:
    build: ./finance
    ports:
      - "8091:8091"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://finance_db:5432/postgres
    depends_on:
      - finance_db

  finance_db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - finance_data:/var/lib/postgresql/data
#finance microservice end

volumes:
  finance_data: