spring:
  application:
    name: ticket-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/aviasales
    username: user
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  sql:
    init:
      platform: postgres
  liquibase:
    change-log: classpath:db/changelog/init.xml

cloud:
  eureka-host: localhost

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${cloud.eureka-host}:8761/eureka/
    enabled: false
