server:
  port: 8080
  forward-headers-strategy: framework

cloud:
  eureka-host: localhost

spring:
  config:
    import: endpoint-mappings.yml
  application:
    name: api-gateway-service

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${cloud.eureka-host}:8761/eureka/
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    beans:
      enabled: true

springfox:
  documentation:
    swagger-ui:
      enabled: true

logging:
  level:
    com.netflix: WARN
    org.springframework.cloud.gateway: DEBUG


swagger:
  config:
    refreshrate: 10000