server:
  port: 8080

cloud:
  eureka-host: localhost
  finance-service-host: finance-service
  userservice-host: userservice
  ticket-service-host: tickets-service

spring:
  application:
    name: api-gateway-service

  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      routes:
        - id: card-service
          uri: lb://${cloud.finance-service-host}
          predicates:
            - Path=/card/**
          filters:
            - AuthFilter=false

        - id: payment-service
          uri: lb://${cloud.finance-service-host}
          predicates:
            - Path=/payment
          filters:
            - AuthFilter=false

        - id: user-service
          uri: lb://${cloud.userservice-host}
          predicates:
            - Path=/users/**
          filters:
            - AuthFilter=true

        - id: auth-service
          uri: lb://${cloud.userservice-host}
          predicates:
            - Path=/auth/**

        - id: ticket-service
          uri: lb://${cloud.ticket-service-host}
          predicates:
            - Path=/tickets/**
          filters:
            - AuthFilter=false

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${cloud.eureka-host}:8761/eureka/
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    beans:
      enabled: true

springfox:
  documentation:
    swagger-ui:
      enabled: true

logging:
  level:
    com.netflix: WARN
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG


swagger:
  config:
    refreshrate: 10000