server:
  port: 8080

cloud:
  eureka-host: localhost
  finance-service-host: finance-service
  userservice-host: userservice
  ticket-service-host: tickets-service
  trip-service-host: tripservice-service
spring:
  application:
    name: api-gateway-service

  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      routes:
        - id: card-service
          uri: lb://${cloud.finance-service-host}
          predicates:
            - Path=/admin/cards/**
          filters:
            - AuthFilter=true

        - id: payment-service
          uri: lb://${cloud.finance-service-host}
          predicates:
            - Path=/payment
          filters:
            - AuthFilter=false

        - id: admin-user-service
          uri: lb://${cloud.userservice-host}
          predicates:
            - Path=/admin/**, /admin
          filters:
            - AuthFilter=true

        - id: guest-user-service
          uri: lb://${cloud.userservice-host}
          predicates:
            - Path=/guest/**, /guest, /auth/**

        - id: user-service
          uri: lb://${cloud.userservice-host}
          predicates:
            - Path=/users/{id}
          filters:
            - UserIdFilter

        - id: ticket-service
          uri: lb://${cloud.ticket-service-host}
          predicates:
            - Path=/tickets/**
          filters:
            - AuthFilter=false

        - id: flight-service-admin
          uri: lb://${cloud.trip-service-host}
          predicates:
              - Path=/flights/admin/**
          filters:
              - AuthFilter=true

        - id: flight-service-guest
          uri: lb://${cloud.trip-service-host}
          predicates:
              - Path=/flights/guest/**

        - id: trip-service-admin
          uri: lb://${cloud.trip-service-host}
          predicates:
            - Path=/trips/admin/**
          filters:
            - AuthFilter=true

        - id: trip-service-guest
          uri: lb://${cloud.trip-service-host}
          predicates:
            - Path=/trips/guest/**

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${cloud.eureka-host}:8761/eureka/
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    beans:
      enabled: true

springfox:
  documentation:
    swagger-ui:
      enabled: true

logging:
  level:
    com.netflix: WARN
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG


swagger:
  config:
    refreshrate: 10000