server:
  port: 8086

cloud:
  eureka-host: localhost
  postgres-host: localhost

spring:
  application:
    name: userservice

  datasource:
    driver-class-name: org.postgresql.Driver
    password: admin
    url: jdbc:postgresql://${cloud.postgres-host}:5432/aviasales?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: postgres

security:
  access_secret: secret
  refresh_secret: refresh
  access_time: 10m
  refresh_time: 30d

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${cloud.eureka-host}:8761/eureka/
    enabled: false





