server:
  port: 8086

spring:
  application:
    name: userservice

  datasource:
    driver-class-name: org.postgresql.Driver
    password: admin
    url: jdbc:postgresql://localhost:5432/aviasales?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: postgres

security:
  access_secret: secret
  refresh_secret: refresh
  access_time: 24h
  refresh_time: 30d