server:
  port: 8085

cloud:
  eureka-host: localhost

spring:
  application:
    name: test-service

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${cloud.eureka-host}:8761/eureka/
    enabled: false




